### ISSUE TITLE
[Low Priority] --verbose option outputs invalid JSON for '----' tags

### ISSUE THREAD

**Issue by coolaj86** [smaniam/mtags#1]
The '----' tags should be expanded to '----[iTunMOVI]', etc just like with --literal.

It is not valid JSON to have multiple tags of the same name.

Immediate solution: add auto-incrementing number '----0', '----1' or create an array '----' : [ {}, {}, {}]

**Comment by smaniam** [comment]
Fixed. Please check and close the Issue.
