### ISSUE TITLE
patch libjson

### ISSUE THREAD

**Issue by coolaj86** [smaniam/mtags#10]
Is it simple to patch libjson for the escape error?

If so, please create and submit the patch via github.

I've marked the issue here:
https://github.com/vincenthz/libjson/issues#issue/5

**Comment by coolaj86** [comment]
Apparently that's a different libjson than the one that you used.

**Comment by coolaj86** [comment]
I submitted a bug to the other libjson (on sourceforge)

http://sourceforge.net/tracker/?func=detail&aid=3132781&group_id=314112&atid=1321773

You would need to e-mail your patch to the maintainer of that project.

**Comment by smaniam** [comment]
Thanks AJ, I had made a patch, apparently the author also made the changes. I have incorporated the patch in github. This should solve the issue

**Comment by smaniam** [comment]
Updated Source
