### ISSUE TITLE
libjson doesn't properly escape existing escape characters "\"

### ISSUE THREAD

**Issue by coolaj86** [smaniam/mtags#11]
I suspect that this will be corrected by the maintainer:
http://sourceforge.net/tracker/?func=detail&aid=3133829&group_id=314112&atid=1321773

```
{
  "ID3v2" : {
    "TRCK" : "11",
    "COMM" : "ALTOMP3 MAKER (YUANSOFT.COM)",
    "TPE1" : "KORINI 11",
    "TIT2" : "TRACK 11"
  },
  "ID3v1" : {
    "title" : "TRACK 11",
    "artist" : "KORINI 11",
    "comment" : "ALTOMP3 MAKER (YUANSOFT.COM)\v"
  }
}
```

This
            "comment" : "ALTOMP3 MAKER (YUANSOFT.COM)\v"

Should be

```
        "comment" : "ALTOMP3 MAKER (YUANSOFT.COM)\\v"
```

**Comment by smaniam** [comment]
\v is the vertical tab - If we assume that is what it represents in the first place - Isn't the behaviour essentially correct? Otherwise we may end up with a lot many backslashes for every round of JSON encapsulation

**Comment by coolaj86** [comment]
Hmm... seems that vertical tab should be escaped as "\u000B" as per JSON.org I'll repost the bug.

**Comment by coolaj86** [comment]
The issue has been corrected in the latest version of libjson. Please update and push changes.

**Comment by smaniam** [comment]
Updated the library
