### ISSUE TITLE
Over- or under-escaped id3 output

### ISSUE THREAD

**Issue by coolaj86** [smaniam/mtags#7]
`\` should be escaped whenever it is not being used to escape `"`

`'` should not be escaped with `\`

```
{
   "ID3v1" : {
        "title" : "Iglesias & W. Houston  \'\' Cou",
        "artist" : "E",
        "genre" : "Blues" 
    }
}
```

**Comment by coolaj86** [comment]
Lot's of things that should not be escaped are. `/` should not be escaped either.

Only `"` and `\` should be escaped

**Comment by smaniam** [comment]
Fixed by patching libjson
