### ISSUE TITLE
ID3V1 tags are normalized when they should be literal

### ISSUE THREAD

**Issue by coolaj86** [smaniam/mtags#8]
`title`, `artist`, and `genre` should not be normalized with the `--literal` option

Also, `genre` should not be resolved to `Blues`. Different clients interpret the different numbers differently. I.E. in iTunes the number may be `Blues`, but in Rythmbox it may be interpreted as `Rock`. I'm not aware of a reliable interpretation for these numbers.

Also, many players simply choose `Blues` when a number is out of range.

```
{
   "ID3v1" : {
        "title" : "Iglesias & W. Houston  \'\' Cou",
        "artist" : "E",
        "genre" : "Blues"
    }
}
```

Better:
    {
        "ID3v2" : {
            "TRCK" : "3\/12",
            "COMM" : [
                "0",
                " 000016C0 0000153D 0000C9B6 000174AC 0000EA63 0000EA63 00008DFA 0000888E 00032187 0000A829",                " 00000000 00000210 00000A68 0000000000900A08 00000000 00562735 00000000 00000000 00000000 00000000 00000000 00000000",  
                "7D09A20C+185114+12+150+14361+31055+47109+61624+76651+90872+108303+121804+138075+154754+168597",
                "3"
            ],
            "TENC" : "iTunes 8.0.2.20",
            "TALB" : "Big Bad World",
            "TIT2" : "Serious Mistake",
            "TPE1" : "Plain White T's",
            "APIC" : {
                "type" : "Other",
                "mime" : "image/png"
            },
            "TCON" : "Alternative & Punk"
        }
    }

**Comment by smaniam** [comment]
I am not sure I understand the requirement of not "Normalizing" - title, artist and genre, 
Can you please elaborate?

Re: "Blues" - do you want me to print the number instead?

**Comment by coolaj86** [comment]
Yes, please print the number instead of "Blues".

**Comment by coolaj86** [comment]
This was a misunderstanding on my part. Id3v1 has no tag names period.
